languageCode = "it"
languageName = "Italiano"
languageDirection = "ltr"
weight = 1

title = "Gabriele Cappellaro"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["proj"]
  description = "Gabriele Cappellaro's portfolio"

[params.author]
  name = "Gabriele Cappellaro"
  image = "img/IMG_5571.jpg"
  headline = "Studente di Ingegneria Informatica in Sapienza"
  bio = "Studente di Ingegneria Informatica in Sapienza"
  links = [
    { instagram = "https://instagram.com/gabrielecappellaro" },
    { github = "https://github.com/cappee" },
    { linkedin = "https://www.linkedin.com/in/gabrielecappellaro/" },
  ]
